entity: baxtub
project: development
experiment: ppo-crafter

seed: 42
n_runs: 1
n_envs: 512
deterministic: true

env:
  id: "Craftax-Classic-Symbolic-v1" # or "Craftax-Classic-Pixels-v1"
  optimistic_resets:
    reset_ratio: 16

agent:
  layer_width: 512

training:
  gamma: 0.99
  gae_lambda: 0.8
  clip_coef: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 1.0
  norm_advantage: true
  clip_vloss: false

  n_steps: 1e6
  n_batch_steps: 64
  n_epochs: 4
  n_minibatches: 8

  lr: 2e-4
  anneal_lr: true

logging: # every n batches
  metrics_every: 1
  # checkpoint_every:  # comment-out to only snapshot at end of training
  # snapshot_every:
